# server
server:
  port: 18000
  servlet:
    context-path: /

spring:
  # 关闭使用thymeleaf
  thymeleaf:
    enabled: false
  application:
    name: springboot-demo
  # 多线程
  thread:
    enabled: true

# 日志追踪
pxc:
  trace:
    enabled: true