# server
server:
  port: 18000
  servlet:
    context-path: /

spring:
  # 关闭使用thymeleaf
  thymeleaf:
    enabled: false
  application:
    name: springboot-demo
  # 多线程
  thread:
    enabled: true
  main:
    web-application-type: servlet

# 日志追踪
pxc:
  trace:
    enabled: true

# 文件存储
file-storage:
  enabled: true
  storage-type: local
  storage-path: /Users/Lypxc/Documents/upload
  local:
    platform: macos

# 自定义插件发布，可热插拔
plugin-ext:
  enabled: false
