# server
server:
  port: 18000
  servlet:
    context-path: /

spring:
  pxc-framework:
    async: true
  operatelog:
    handler: io.github.test.handle.OperateLogHandler
    log-type: other
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  application:
    name: springboot-demo
  redis:
    url: 127.0.0.1
    port: 6379
    database: 0
  profiles:
    active: undertow
#    key-prefix: pxc
